var sets = {
	1 : {
		name : "Base",
		releaseDate : "10/2008",
	},
	2 : {
		name : "Intrigue",
		releaseDate : "7/2009",
	},
	3 : {
		name : "Seaside",
		releaseDate : "10/2009",
	},
	4 : {
		name : "Alchemy",
		releaseDate : "5/2010",
	},
	5 : {
		name : "Prosperity",
		releaseDate : "10/2010",
	},
	6 : {
		name : "Cornucopia",
		releaseDate : "6/2011",
	},
	7 : {
		name : "Hinterlands",
		releaseDate : "10/2011",
	},
	8 : {
		name : "Dark Ages",
		releaseDate : "",
	},
	9 : {
		name : "Guilds",
		releaseDate : "",
	},
	10: {
		name : "Adventures",
		releaseDate : "4/2015",
	},
	11 : {
		name : "Promo",
		releaseDate : "3/2009",
	}
};




var cards = [
	{
		name : "Adventurer",
		setID : 1,
		isAction : true,
		cost : 6,
		description : "Reveal cards from your deck until you reveal 2 Treasure cards. Put those Treasure cards into your hand and discard the other revealed cards.",
	},
	{
		name : "Bureaucrat",
		setID : 1,
		isAction : true,
		isAttack : true,
		cost : 4,
		description : "Gain a Silver Card: put it on top of your deck. Each other player reveals a Victory card from his hand and puts it on his deck (or reveals a hand with no Victory cards)",
	},
	{
		name : "Cellar",
		setID : 1,
		isAction : true,
		cost : 2,
		actions : 1,
		description : "Discard any number of cards. +1 Card per card discarded.",
	},
	{
		name : "Chancellor",
		setID : 1,
		isAction : true,
		cost : 3,
		coins : 2,
		description : "You may immediately put your deck into your discard pile.",
	},
	{
		name : "Chapel",
		setID : 1,
		isAction : true,
		isTrasher: true,
		cost : 2,
		description : "Trash up to 4 cards from your hand.",
	},
	{
		name : "Council Room",
		setID : 1,
		isAction : true,
		cost : 5,
		cards : 4,
		buys : 1,
		description : "Each other player draws a card.",
	},
	{
		name : "Feast",
		setID : 1,
		isAction : true,
		cost : 4,
		description : "Trash this card. Gain a card costing up to 5 Coins.",
	},
	{
		name : "Festival",
		setID : 1,
		isAction : true,
		cost : 5,
		actions : 2,
		coins : 2,
		buys : 1,
		description : "",
	},
	{
		name : "Gardens",
		setID : 1,
		isVictory : true,
		cost : 4,
		description : "Worth 1 VP for every 10 cards in your deck (rounded down).",
	},
	{
		name : "Laboratory",
		setID : 1,
		isAction : true,
		cost : 5,
		cards : 2,
		actions : 1,
		description : "",
	},
	{
		name : "Library",
		setID : 1,
		isAction : true,
		cost : 5,
		description : "Draw until you have 7 cards in hand. You may set aside any Action cards drawn this way, as you draw them, discard the set aside cards after you finish drawing.",
	},
	{
		name : "Market",
		setID : 1,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		coins : 1,
		buys : 1,
		description : "",
	},
	{
		name : "Militia",
		setID : 1,
		isAction : true,
		isAttack : true,
		cost : 4,
		coins : 2,
		description : "Each other player discards down to 3 cards in his hand.",
	},
	{
		name : "Mine",
		setID : 1,
		isAction : true,
		cost : 5,
		description : "Trash a Treasure card from your hand. Gain a Treasure card costing up to 3 Coins more, put it into your hand."
	},
	{
		name : "Moat",
		setID : 1,
		isAction : true,
		isReaction : true,
		isMoat: true,
		cost : 2,
		cards : 2,
		description : "[Action]: Draw 2 Cards. [Reaction]: When another player plays an Attack card, you may reveal this from your hand. If you do, you are unaffected by that attack.",
	},
	{
		name : "Moneylender",
		setID : 1,
		isAction : true,
		isTrasher: true,
		cost : 4,
		description : "Trash a Copper card from your hand. If you do, +3 Coins.",
	},
	{
		name : "Remodel",
		setID : 1,
		isAction : true,
		cost : 4,
		description : "Trash a card from your hand. Gain a card costing up to 2 Coins more than the trashed card.",
	},
	{
		name : "Smithy",
		setID : 1,
		isAction : true,
		cost : 4,
		cards : 3,
		description : "",
	},
	{
		name : "Spy",
		setID : 1,
		isAction : true,
		isAttack : true,
		cost : 4,
		cards : 1,
		actions : 1,
		description : "Each player (including you) reveals the top card of his deck and either discards it or puts it back, your choice.",
	},
	{
		name : "Thief",
		setID : 1,
		isAction : true,
		isAttack : true,
		cost : 4,
		description : "Each other player reveals the top 2 cards of his deck. If they revealed ant Treasure cards, they trash one of them that you choose. You may gain any or all of these trashed cards. They discard the other revealed cards.",
	},
	{
		name : "Throne Room",
		setID : 1,
		isAction : true,
		cost : 4,
		description : "Choose an Action card in your hand. Play it Twice.",
	},
	{
		name : "Village",
		setID : 1,
		isAction : true,
		cost : 3,
		cards : 1,
		actions : 2,
		description : "",
	},
	{
		name : "Witch",
		setID : 1,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 5,
		cards : 2,
		description : "Each other player gains a Curse card.",
	},
	{
		name : "Woodcutter",
		setID : 1,
		isAction : true,
		cost : 3,
		coins : 2,
		buys : 1,
		description : "",
	},
	{
		name : "Workshop",
		setID : 1,
		isAction : true,
		cost : 3,
		description : "Gain a card costing up to 4 Coins.",
	},
	{
		name : "Baron",
		setID : 2,
		isAction : true,
		cost : 4,
		buys : 1,
		description : "You may discard an estate card. If you do, +4 Coin. Otherwise, gain an estate card.",
	},
	{
		name : "Bridge",
		setID : 2,
		isAction : true,
		cost : 4,
		coins : 1,
		buys : 1,
		description : "All cards (including cards in playersÕ hands) cost 1 Coin less this turn, but no less than 0 Coin.",
	},
	{
		name : "Conspirator",
		setID : 2,
		isAction : true,
		cost : 4,
		coins : 2,
		description : "If you played 3 or more Actions this turn (counting this): +1 Card, +1 Action",
	},
	{
		name : "Coppersmith",
		setID : 2,
		isAction : true,
		cost : 4,
		description : "Copper produces an extra 1 Coin this turn.",
	},
	{
		name : "Courtyard",
		setID : 2,
		isAction : true,
		cost : 2,
		cards : 3,
		description : "Put a card from your hand on top of your deck.",
	},
	{
		name : "Duke",
		setID : 2,
		isVictory : true,
		cost : 5,
		description : "Worth 1 VP for each Duchy you have.",
	},
	{
		name : "Great Hall",
		setID : 2,
		isAction : true,
		isVictory : true,
		cost : 3,
		cards : 1,
		actions : 1,
		victoryPoints : 1,
		description : "",
	},
	{
		name : "Harem",
		setID : 2,
		isTreasure : true,
		isVictory : true,
		cost : 6,
		// coins : 2,
		victoryPoints : 2,
		description : "",
	},
	{
		name : "Ironworks",
		setID : 2,
		isAction : true,
		cost : 4,
		description : "Gain a card costing up to 4 Coins. If it is anÉ Action card, +1 Action. Treasure card, +1 Coin. Victory card, +1 Card.",
	},
	{
		name : "Masquerade",
		setID : 2,
		isAction : true,
		isTrasher: true,
		cost : 3,
		description : "Each player passes a card from his hand to the left at once. Then you may trash a card from your hand.",
	},
	{
		name : "Mining Village",
		setID : 2,
		isAction : true,
		cost : 4,
		cards : 1,
		actions : 2,
		description : "You may trash this card immediately, If you do, +2 Coins.",
	},
	{
		name : "Minion",
		setID : 2,
		isAction : true,
		cost : 5,
		actions : 1,
		description : "Choose one: +2 Coins, or discard your hand, + 4 cards, and each other player with at least 5 cards in hand discards his hand and draws 4 cards.",
	},
	{
		name : "Nobles",
		setID : 2,
		isAction : true,
		isVictory : true,
		cost : 6,
		victoryPoints : 2,
		description : "Choose one: +3 Cards, or +2 Actions.",
	},
	{
		name : "Pawn",
		setID : 2,
		isAction : true,
		cost : 2,
		description : "Choose two: +1 Card, +1 Action, +1 Buy, +1 Coin. (The choices must be different)",
	},
	{
		name : "Saboteur",
		setID : 2,
		isAction : true,
		isAttack : true,
		cost : 5,
		description : "Each other player reveals cards from the top of his deck until revealing one costing 3 Coins or more. He trashes that card and may gain a card costing at most 2 Coins less than it. He discards the other revealed cards.",
	},
	{
		name : "Scout",
		setID : 2,
		isAction : true,
		cost : 4,
		description : "Reveal the top 4 cards of your deck. Put the revealed Victory cards into your hand. Put the other cards on top your deck in any order.",
	},
	{
		name : "Secret Chamber",
		setID : 2,
		isAction : true,
		isReaction : true,
		cost : 2,
		description : "[Action]: Discard any number of cards. +1 Coin for per card discarded. [Reaction]: When another player plays an Attack card, you may reveal this from your hand. If you do, +2 Cards, then put 2 cards from your hand on top of your deck.",
	},
	{
		name : "Shanty Town",
		setID : 2,
		isAction : true,
		cost : 3,
		actions : 2,
		description : "Reveal your hand. If you have no actions cards in hand, +2 Cards.",
	},
	{
		name : "Steward",
		setID : 2,
		isAction : true,
		isTrasher: true,
		cost : 3,
		description : "Choose one: +2 cards, or +2 Coins, or trash 2 cards from your hand.",
	},
	{
		name : "Swindler",
		setID : 2,
		isAction : true,
		isAttack : true,
		cost : 3,
		coins : 2,
		description : "Each other player trashes the top card of his deck and gains a card of the same cost that you choose.",
	},
	{
		name : "Torturer",
		setID : 2,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 5,
		cards : 3,
		description : "Each other player chooses one: he discards 2 cards, or he gains a Curse card, putting it in his hand.",
	},
	{
		name : "Trading Post",
		setID : 2,
		isAction : true,
		isTrasher: true,
		cost : 5,
		description : "Trash 2 cards from your hand. If you do, gain a Silver card, put it into your hand.",
	},
	{
		name : "Tribute",
		setID : 2,
		isAction : true,
		cost : 5,
		description : "The player to your left reveals and then discards the top 2 cards of his deck. For each different named card revealed, if it is an... Action card, +2 Actions, Treasure card, +2 Coins, Victory Card, +2 Cards",
	},
	{
		name : "Upgrade",
		setID : 2,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		description : "Trash a card form your hand. Gain a card costing exactly 1 Coin more than it.",
	},
	{
		name : "Wishing Well",
		setID : 2,
		isAction : true,
		cost : 3,
		cards : 1,
		actions : 1,
		description : "Name a card. Reveal the top card of your deck. If itÕs the named card, put it into your hand.",
	},
	{
		name : "Ambassador",
		setID : 3,
		isAction : true,
		isAttack : true,
		isTrasher: true,
		cost : 3,
		description : "Reveal a card from your hand. Return up to 2 copies of it from your hand to the Supply. Then each other player gains a copy of it.",
	},
	{
		name : "Bazaar",
		setID : 3,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 2,
		coins : 1,
		description : "",
	},
	{
		name : "Caravan",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 4,
		cards : 1,
		actions : 1,
		description : "At the start of your next turn, +1 Card.",
	},
	{
		name : "Cutpurse",
		setID : 3,
		isAction : true,
		isAttack : true,
		cost : 4,
		coins : 2,
		description : "Each other player discards a Copper card (or reveals a hand with no Copper).",
	},
	{
		name : "Embargo",
		setID : 3,
		isAction : true,
		cost : 2,
		coins : 2,
		description : "Trash this card. Put an Embargo token on top of a Supply pile. When a player buys a card, he gains a Curse card per Embargo token on that pile.",
	},
	{
		name : "Explorer",
		setID : 3,
		isAction : true,
		cost : 5,
		description : "You may reveal a Province card from your hand. If you do, gain a Gold card, putting it into your hand. Otherwise, gain a Silver card, putting it into your hand.",
	},
	{
		name : "Fishing Village",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 3,
		actions : 2,
		coins : 1,
		description : "At the start of your next turn: +1 Action, +1 Coin.",
	},
	{
		name : "Ghost Ship",
		setID : 3,
		isAction : true,
		isAttack : true,
		cost : 5,
		cards : 2,
		description : "Each other player with 4 or more cards in hand puts cards from his hand on top of his deck until he has 3 cards in his hand.",
	},
	{
		name : "Haven",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 2,
		cards : 1,
		actions : 1,
		description : "Set aside a card from your hand face down. At the start of your next turn, put it into your hand.",
	},
	{
		name : "Island",
		setID : 3,
		isAction : true,
		isVictory : true,
		cost : 4,
		victoryPoints : 2,
		description : "Set aside this and another card from your hand. Return them to your deck at the end of the game.",
	},
	{
		name : "Lighthouse",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 2,
		actions : 1,
		description : "Now and at the start of your next turn: +1 Coin. While this is in play, when another player plays an Attack card, it doesnÕt affect you.",
	},
	{
		name : "Lookout",
		setID : 3,
		isAction : true,
		cost : 3,
		actions : 1,
		description : "Look at the top 3 cards of your deck. Trash one of them. Discard one of them. Put the other one on top of your deck.",
	},
	{
		name : "Merchant Ship",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 5,
		coins : 2,
		description : "Now and at the start of your next turn: +2 Coins.",
	},
	{
		name : "Native Village",
		setID : 3,
		isAction : true,
		cost : 2,
		actions : 2,
		description : "Choose one: Set aside the top card of your deck face down on your Native Village mat, or put all the cards from your mat into your hand. You may look at the cards on your mat at any time, return them to your deck at the end of the game.",
	},
	{
		name : "Navigator",
		setID : 3,
		isAction : true,
		cost : 4,
		coins : 2,
		description : "Look at the top 5 cards of your deck. Either discard all of them, or put them back on top of your deck in any order.",
	},
	{
		name : "Outpost",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 5,
		description : "You only draw 3 cards (instead of 5) in this turnÕs Clean-up phase. Take an extra turn after this one. This canÕt cause you to take more than two consecutive turns.",
	},
	{
		name : "Pearl Diver",
		setID : 3,
		isAction : true,
		cost : 2,
		cards : 1,
		actions : 1,
		description : "Look at the bottom card of your deck. You may put it on top.",
	},
	{
		name : "Pirate Ship",
		setID : 3,
		isAction : true,
		isAttack : true,
		cost : 4,
		description : "Choose one: Each other player reveals the top 2 cards of his deck, trashes a revealed Treasure that you choose, discards the rest, and if anyone trashed a Treasure you take a Coin token, or, +1 Coin per Coin token youÕve taken with Pirate Ships this game.",
	},
	{
		name : "Salvager",
		setID : 3,
		isAction : true,
		isTrasher: true,
		cost : 4,
		buys : 1,
		description : "Trash a card from your hand. + Coin equal to its cost.",
	},
	{
		name : "Sea Hag",
		setID : 3,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 4,
		description : "Each other player discards the top card of his deck, then gains a Curse card, putting it on top of his deck.",
	},
	{
		name : "Smugglers",
		setID : 3,
		isAction : true,
		cost : 3,
		description : "Gain a copy of a card costing up to 6 Coins that the player to your right gained on his last turn.",
	},
	{
		name : "Tactician",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 5,
		description : "Discard your hand. If you discarded any cards this way, then at the start of your next turn, +5 Cards, +1 Buy, and +1 Action.",
	},
	{
		name : "Treasure Map",
		setID : 3,
		isAction : true,
		cost : 4,
		description : "Trash this and another copy of Treasure Map from your hand. If you do trash two Treasure Maps, gain 4 Gold cards, putting them on top of your deck.",
	},
	{
		name : "Treasury",
		setID : 3,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		coins : 1,
		description : "When you discard this from play, if you didnÕt buy a Victory card this turn, you may put this on top of your deck.",
	},
	{
		name : "Warehouse",
		setID : 3,
		isAction : true,
		cost : 3,
		cards : 3,
		actions : 1,
		description : "Discard 3 cards.",
	},
	{
		name : "Wharf",
		setID : 3,
		isAction : true,
		isDuration : true,
		cost : 5,
		cards : 2,
		buys : 1,
		description : "Now and at the start of your next turn: +2 Cards, +1 Buy.",
	},
	{
		name : "Alchemist",
		setID : 4,
		isAction : true,
		cost : 3,
		potion : true,
		cards : 2,
		actions : 1,
		description : "When you discard this from play, you may put this on top of your deck if you have a Potion in play.",
	},
	{
		name : "Apothecary",
		setID : 4,
		isAction : true,
		cost : 2,
		potion : true,
		cards : 1,
		actions : 1,
		description : "Reveal the top 4 cards of your deck. Put the revealed Coppers and Potions into your hand. Put the other cards back on top of your deck in any order.",
	},
	{
		name : "Apprentice",
		setID : 4,
		isAction : true,
		isTrasher: true,
		cost : 5,
		actions : 1,
		description : "Trash a card from your hand. +1 Card per Coin it costs. +2 Cards if it has Potion in its cost.",
	},
	{
		name : "Familiar",
		setID : 4,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 3,
		potion : true,
		cards : 1,
		actions : 1,
		description : "Each other player gains a Curse.",
	},
	{
		name : "Golem",
		setID : 4,
		isAction : true,
		cost : 4,
		potion : true,
		description : "Reveal cards from your deck until you reveal 2 Action cards other than Golem cards. Discard the other cards, then play the Action cards in either order.",
	},
	{
		name : "Herbalist",
		setID : 4,
		isAction : true,
		cost : 2,
		coins : 1,
		buys : 1,
		description : "When you discard this from play, you may put one of your Treasures from play on top of your deck.",
	},
	{
		name : "Philosopher's Stone",
		setID : 4,
		isTreasure : true,
		cost : 3,
		potion : true,
		description : "When you play this, count your deck and discard pile. Worth 1 Coin per 5 cards total between them (rounded down).",
	},
	{
		name : "Possession",
		setID : 4,
		isAction : true,
		cost : 6,
		potion : true,
		description : "The player to your left takes an extra turn after this one, in which you can see all cards he can and make all decisions for him. Any cards he would gain on that turn, you gain instead, any cards of his that are trashed are set aside and returned to his deck.",
	},
	{
		name : "Scrying Pool",
		setID : 4,
		isAction : true,
		cost : 2,
		potion : true,
		actions : 1,
		description : "Each player (including you) reveals the top card of his deck and either discards it or puts it back, your choice. Then reveal cards from the top of your deck until revealing one that isnÔt an Action. Put all of your revealed cards into your hand.",
	},
	{
		name : "Transmute",
		setID : 4,
		isAction : true,
		cost : 0,
		potion : true,
		description : "Trash a card from your hand. If it is aÉ  Action card, gain a Duchy. Treasure card, gain a Transmute. Victory card, gain a Gold.",
	},
	{
		name : "University",
		setID : 4,
		isAction : true,
		cost : 2,
		potion : true,
		actions : 2,
		description : "You may gain an Action card costing up to 5 Coins.",
	},
	{
		name : "Vineyard",
		setID : 4,
		isVictory : true,
		cost : 1,
		potion : true,
		description : "Worth 1 VP for every 3 Action cards in your deck (rounded down).",
	},
	{
		name : "Bank",
		setID : 5,
		isTreasure : true,
		cost : 7,
		description : "When you play this, itÕs worth 1 Coin per Treasure card you have in play (counting this).",
	},
	{
		name : "Bishop",
		setID : 5,
		isAction : true,
		isTrasher: true,
		cost : 4,
		description : "",
	},
	{
		name : "City",
		setID : 5,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 2,
		description : "If there are one or more empty Supply piles, +1 Card. If there are two or more, +1 Coin and +1 Buy.",
	},
	{
		name : "Contraband",
		setID : 5,
		isTreasure : true,
		cost : 5,
		coins : 3,
		buys : 1,
		description : "When you play this, the player to your left names a card. You canÕt buy that card this turn.",
	},
	{
		name : "Counting House",
		setID : 5,
		isAction : true,
		cost : 5,
		description : "Look through your discard pile, reveal any number of Copper cards from it, and put them into your hand.",
	},
	{
		name : "Expand",
		setID : 5,
		isAction : true,
		cost : 7,
		description : "Trash a card from your hand. Gain a card costing up to 3 Coins more than the trashed card.",
	},
	{
		name : "Forge",
		setID : 5,
		isAction : true,
		isTrasher: true,
		cost : 7,
		description : "Trash any number of cards from your hand. Gain a card with cost exactly equal to the total cost in Coins of the trashed cards.",
	},
	{
		name : "Goons",
		setID : 5,
		isAction : true,
		isAttack : true,
		cost : 6,
		coins : 2,
		buys : 1,
		description : "Each other player discards down to 3 cards in hand. While this is in play, when you buy a card, +1 VP.",
	},
	{
		name : "Grand Market",
		setID : 5,
		isAction : true,
		cost : 6,
		cards : 1,
		actions : 1,
		coins : 2,
		buys : 1,
		description : "You canÕt buy this if you have any Copper in play.",
	},
	{
		name : "Hoard",
		setID : 5,
		isTreasure : true,
		cost : 6,
		coins : 2,
		description : "While this is in play, when you buy a Victory card, gain a Gold.",
	},
	{
		name : "King's Court",
		setID : 5,
		isAction : true,
		cost : 7,
		description : "You may choose an Action card in your hand. Play it three times.",
	},
	{
		name : "Loan",
		setID : 5,
		isTreasure : true,
		isTrasher: true,
		cost : 3,
		coins : 1,
		description : "When you play this, reveal cards from your deck until you reveal a Treasure. Discard it or trash it. Discard the other cards.",
	},
	{
		name : "Mint",
		setID : 5,
		isAction : true,
		isTrasher: true,
		cost : 5,
		description : "You may reveal a Treasure card from your hand. Gain a copy of it. then you buy this, trash all Treasures you have in play.",
	},
	{
		name : "Monument",
		setID : 5,
		isAction : true,
		cost : 4,
		coins : 2,
		victoryPoints : 1,
		description : "",
	},
	{
		name : "Mountebank",
		setID : 5,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 5,
		coins : 2,
		description : "Each other player may discard a Curse. If he doesnÕt, he gains a Curse and a Copper.",
	},
	{
		name : "Peddler",
		setID : 5,
		isAction : true,
		cost : 8,
		cards : 1,
		actions : 1,
		coins : 1,
		description : "During your Buy phase, this costs 2 Coins less per Action card you have in play, but not less than 0 Coin.",
	},
	{
		name : "Quarry",
		setID : 5,
		isTreasure : true,
		cost : 4,
		coins : 1,
		description : "While this is in play, Action cards cost 2 Coins less, but not less than 0 Coin.",
	},
	{
		name : "Rabble",
		setID : 5,
		isAction : true,
		isAttack : true,
		cost : 5,
		cards : 3,
		description : "Each other player reveals the top 3 cards of his deck, discards the revealed Actions and Treasures, and puts the rest back on top in any order he chooses.",
	},
	{
		name : "Royal Seal",
		setID : 5,
		isTreasure : true,
		cost : 5,
		coins : 2,
		description : "While this is in play, when you gain a card, you may put that card on top of your deck.",
	},
	{
		name : "Talisman",
		setID : 5,
		isTreasure : true,
		cost : 4,
		coins : 1,
		description : "While this is in play, when you buy a card costing 4 Coins or less that is not a Victory card, gain a copy of it.",
	},
	{
		name : "Trade Route",
		setID : 5,
		isAction : true,
		isTrasher: true,
		cost : 3,
		buys : 1,
		description : "+1 Coin per token on the Trade Route mat. Trash a card from your hand. [Setup]: Put a token on each Victory card Supply pile. When a card is gained from that pile, move the token to the Trade Route mat.",
	},
	{
		name : "Vault",
		setID : 5,
		isAction : true,
		cost : 5,
		cards : 2,
		description : "Discard any number of cards. +1 Coin per card discarded. Each other player may discard 2 cards. If he does, he draws a card.",
	},
	{
		name : "Venture",
		setID : 5,
		isTreasure : true,
		cost : 5,
		coins : 1,
		description : "When you play this, reveal cards from your deck until you reveal a Treasure. Discard the other cards. Play that Treasure.",
	},
	{
		name : "Watchtower",
		setID : 5,
		isAction : true,
		isReaction : true,
		cost : 3,
		description : "[Action]: Draw until you have 6 cards in hand. [Reaction]: When you gain a card, you may reveal this from your hand. If you do, either trash that card, or put it on top of your deck.",
	},
	{
		name : "Worker's Village",
		setID : 5,
		isAction : true,
		cost : 4,
		cards : 1,
		actions : 2,
		buys : 1,
		description : "",
	},
	{
		name : "Fairgrounds",
		setID : 6,
		isVictory : true,
		cost : 6,
		description : "Worth 2 VP for every 5 differently named cards in your deck (rounded down).",
	},
	{
		name : "Farming Village",
		setID : 6,
		isAction : true,
		cost : 4,
		actions : 2,
		description : "Reveal cards from the top of your deck until you reveal an Action or Treasure card. Put that card into your hand and discard the other cards.",
	},
	{
		name : "Fortune Teller",
		setID : 6,
		isAction : true,
		isAttack : true,
		cost : 3,
		cards : 2,
		description : "Each other player reveals cards from the top of his deck until he reveals a Victory or Curse card. He puts it on top and discards  the other revealed cards.",
	},
	{
		name : "Hamlet",
		setID : 6,
		isAction : true,
		cost : 2,
		cards : 1,
		actions : 1,
		description : "You may discard a card, if you do +1 Action. You may discard a card, if you do +1 Buy.",
	},
	{
		name : "Harvest",
		setID : 6,
		isAction : true,
		cost : 5,
		description : "Reveal the top 4 cards of your deck, then discard them. +1 Coin per differently named card revealed.",
	},
	{
		name : "Horn of Plenty",
		setID : 6,
		isTreasure : true,
		cost : 5,
		description : "When you play this, gain a card costing up to 1 Coin per differently named card you have in play, counting this. If itÕs a Victory card, trash this.",
	},
	{
		name : "Horse Traders",
		setID : 6,
		isAction : true,
		isReaction : true,
		cost : 4,
		buys : 1,
		coins : 3,
		description : "[Action]: Discard 2 Cards. [Reaction]: When another player plays an Attack card, you may set this aside from your hand. If you do, then at the start of your next turn, +1 Card and return this to your hand.",
	},
	{
		name : "Hunting Party",
		setID : 6,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		description : "Reveal your hand. Reveal cards from your deck until you reveal a card that isnÕt a duplicate of one in your hand. Put it into your hand and discard the rest.",
	},
	{
		name : "Jester",
		setID : 6,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 5,
		coins : 2,
		description : "Each other player discards the top card of his deck. If itÕs a Victory card he gains a Curse. Otherwise he gains a copy of the discarded card or you do, your choice.",
	},
	{
		name : "Menagerie",
		setID : 6,
		isAction : true,
		cost : 3,
		actions : 1,
		description : "Reveal your hand. If there are no duplicate cards in it, +3 Cards. Otherwise, +1 Card.",
	},
	{
		name : "Remake",
		setID : 6,
		isAction : true,
		cost : 4,
		description : "Do this twice: Trash a card from your hand then gain a card costing exactly 1 Coin more than the trashed card.",
	},
	{
		name : "Tournament",
		setID : 6,
		isAction : true,
		cost : 4,
		actions : 1,
		description : "Each player may reveal a Provence from his hand. If you do, discard it and gain a Prize (from the Prize pile) or a Duchy, putting it on top of your deck. If no one else does, +1 Card, +1 Coin.",
	},
	{
		name : "Young Witch",
		setID : 6,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 4,
		cards : 2,
		description : "Each other player may reveal a Bane card from his hand. If he doesnÕt, he gains a Curse. [Set-up]: Add an extra Kingdom card pile costing 2 Coins or 3 Coins to the supply. Cards from that pile are Bane cards.",
	},
	{
		name : "Border Village",
		setID : 7,
		isAction : true,
		cost : 6,
		cards : 1,
		actions : 2,
		description : "When you gain this, gain a card costing less than this.",
	},
	{
		name : "Cache",
		setID : 7,
		isTreasure : true,
		cost : 5,
		coins : 3,
		description : "When you gain this, gain two Coppers.",
	},
	{
		name : "Cartographer",
		setID : 7,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		description : "Look at the top 4 cards of your deck. Discard any number of them. Put the rest back on top in any order.",
	},
	{
		name : "Crossroads",
		setID : 7,
		isAction : true,
		cost : 2,
		description : "Reveal your hand. +1 Card per Victory card revealed. If this is the first time you played Crossroads this turn, +3 Actions.",
	},
	{
		name : "Develop",
		setID : 7,
		isAction : true,
		cost : 3,
		description : "Trash a card from your hand. Gain a card costing exactly 1 Coin more than it and a card costing exactly 1 Coin less than it, in either order, putting them on top of your deck.",
	},
	{
		name : "Duchess",
		setID : 7,
		isAction : true,
		cost : 2,
		coins : 2,
		description : "Each player (including you) looks at the top card of his deck, and discards it or puts it back. In games using this, when you gain a Duchy, you may gain a Duchess.",
	},
	{
		name : "Embassy",
		setID : 7,
		isAction : true,
		cost : 5,
		cards : 5,
		description : "Discard 3 cards. When you gain this, each other player gains a Silver.",
	},
	{
		name : "Farmland",
		setID : 7,
		isVictory : true,
		cost : 6,
		victoryPoints : 2,
		description : "When you buy this, trash a card from your hand. Gain a card costing exactly 2 Coins more than the trashed card.",
	},
	{
		name : "Fool's Gold",
		setID : 7,
		isTreasure : true,
		isReaction : true,
		cost : 2,
		description : "[Treasure]: If this is the first time you played a Fool's Gold this turn, this is worth 1 Coin, otherwise it's worth 4 Coins. [Reaction]: When another player gains a Province, you may trash this from your hand. If you do, gain a Gold, putting it on your deck.",
	},
	{
		name : "Haggler",
		setID : 7,
		isAction : true,
		cost : 5,
		coins : 2,
		description : "While this is in play, when you buy a card, gain a card costing less than it that is not a Victory card.",
	},
	{
		name : "Highway",
		setID : 7,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		description : "While this is in play, cards cost 1 Coin less, but not less than 0 Coins.",
	},
	{
		name : "Ill-Gotten Gains",
		setID : 7,
		isCurser: true,
		isTreasure : true,
		cost : 5,
		coins : 1,
		description : "When you play this, may gain a Copper, putting it into your hand. When you gain this, each other player gains a Curse.",
	},
	{
		name : "Inn",
		setID : 7,
		isAction : true,
		cost : 5,
		cards : 2,
		actions : 2,
		description : "Discard 2 cards. When you gain this, look through your discard pile (including this), reveal any number of Action cards from it, and shuffle them into your deck.",
	},
	{
		name : "Jack of all Trades",
		setID : 7,
		isAction : true,
		cost : 4,
		description : "Gain a Silver. Look at the top card of your deck, discard it or put it back. Draw until you have 5 cards in hand. You may trash a card from your hand that is not a Treasure.",
	},
	{
		name : "Mandarin",
		setID : 7,
		isAction : true,
		cost : 5,
		coins : 3,
		description : "Put a card from your hand on top of your deck. When you gain this, put all Treasures you have in play on top of your deck in any order.",
	},
	{
		name : "Margrave",
		setID : 7,
		isAction : true,
		isAttack : true,
		cost : 5,
		cards : 3,
		buys : 1,
		description : "Each other player draws a card, then discards down to 3 cards in hand.",
	},
	{
		name : "Noble Brigand",
		setID : 7,
		isAction : true,
		isAttack : true,
		cost : 4,
		coins : 1,
		description : "When you buy this or play it, each other player reveals the top 2 cards of his deck, trashes a revealed Silver or Gold you choose, and discards the rest. If he didn't reveal a Treasure, he gains a Copper. You gain the trashed cards.",
	},
	{
		name : "Nomad Camp",
		setID : 7,
		isAction : true,
		cost : 4,
		coins : 2,
		buys : 1,
		description : "When you gain this, put it on top of your deck.",
	},
	{
		name : "Oasis",
		setID : 7,
		isAction : true,
		cost : 3,
		cards : 1,
		actions : 1,
		coins : 1,
		description : "Discard a card.",
	},
	{
		name : "Oracle",
		setID : 7,
		isAction : true,
		isAttack : true,
		cost : 3,
		cards : 2,
		description : "Each player (including you) reveals the top 2 cards of his deck, and you choose one: either he discards them, or he puts them back on top in an order he chooses.",
	},
	{
		name : "Scheme",
		setID : 7,
		isAction : true,
		cost : 3,
		cards : 1,
		actions : 1,
		description : "At the start of Clean-up this turn, you may choose an Action card you have in play. If you discard it from play this turn, put it on your deck.",
	},
	{
		name : "Silk Road",
		setID : 7,
		isVictory : true,
		cost : 4,
		description : "Worth 1 VP for every 4 Victory cards in your deck (round down).",
	},
	{
		name : "Spice Merchant",
		setID : 7,
		isAction : true,
		isTrasher: true,
		cost : 4,
		description : "You may trash a Treasure from your hand. If you do, choose one: +2 Cards and +1 Action, or +2 Coins and +1 Buy.",
	},
	{
		name : "Stables",
		setID : 7,
		isAction : true,
		cost : 5,
		description : "You may discard a Treasure. If you do, +3 Cards and +1 Action.",
	},
	{
		name : "Trader",
		setID : 7,
		isAction : true,
		isReaction : true,
		isTrasher: true,
		cost : 4,
		description : "[Action]: Trash a card from your hand. Gain a number of silvers equal to its cost in Coins. [Reaction]: When you would gain a card, you may reveal this from your hand. If you do, instead, gain a silver.",
	},
	{
		name : "Tunnel",
		setID : 7,
		isVictory : true,
		isReaction : true,
		cost : 3,
		victoryPoints : 2,
		description : "When you discard this other than during a Clean-up phase, you may reveal it. If you do, gain a Gold.",
	},
	{
		name : "Madman",
		setID : 8,
		isAction : true,
		excludeFromSupply : true,
		cost : 0,
		actions: 2,
		description : "Return this to the Madman pile. If you do, +1 Card per card in your hand. (This is not in the Supply.)",
	},
	{
		name : "Mercenary",
		setID : 8,
		isAction : true,
		isAttack : true,
		isTrasher: true,
		excludeFromSupply : true,
		cost : 0,
		description : "You may trash 2 cards from your hand. If you do, +2 Cards, + $2, and each other player discards down to 3 cards in hand. (This is not in the Supply.)",
	},
	{
		name : "Spoils",
		setID : 8,
		isTreasure : true,
		excludeFromSupply : true,
		cost : 0,
		coins: 3,
		description : "When you play this, return it to the pile.",
	},
	{
		name : "Poor House",
		setID : 8,
		isAction : true,
		cost : 1,
		coins: 4,
		description : "Reveal your hand. -$1 per Treasure card in your hand, to a minimum of $0.",
	},
	{
		name : "Beggar",
		setID : 8,
		isAction : true,
		isReaction : true,
		cost : 2,
		description : "[Action]: Gain 3 Coppers, putting them into your hand. [Reaction]: When another player plays an Attack card, you may discard this. If you do, gain two Silvers, putting one on top of your deck.",
	},
	{
		name : "Squire",
		setID : 8,
		isAction : true,
		cost : 2,
		coins: 1,
		description : "[Action]: Choose one: +2 Actions; or +2 Buys; or gain a Silver. [Trash]: When you trash this, gain an Attack card.",
	},
	{
		name : "Vagrant",
		setID : 8,
		isAction : true,
		cost : 2,
		cards: 1,
		actions: 1,
		coins: 1,
		description : "Reveal the top card of your deck. If itÕs a Victory card, Curse, Ruins, or Shelter, put it into your hand.",
	},
	{
		name : "Hermit",
		setID : 8,
		isAction : true,
		isTrasher: true,
		cost : 3,
		description : "[Action]: Look through your discard pile. You may trash a card that is not a Treasure, from your discard pile or your hand. Gain a card costing up to $3. [Discard]: When you discard this from play, if you didnÕt buy any cards this turn, trash this and gain a Madman (from the Madman pile).",
	},
	{
		name : "Forager",
		setID : 8,
		isAction : true,
		isTrasher: true,
		cost : 3,
		actions: 1,
		buys: 1,
		description : "Trash a card from your hand. +$1 per differently named Treasure in the trash.",
	},
	{
		name : "Market Square",
		setID : 8,
		isAction : true,
		isReaction : true,
		cost : 3,
		cards: 1,
		actions: 1,
		buys: 1,
		description : "[Reaction]: When one of your cards is trashed, you may discard this from your hand. If you do, gain a Gold.",
	},
	{
		name : "Sage",
		setID : 8,
		isAction : true,
		cost : 3,
		actions: 1,
		description : "Reveal cards from the top of your deck until you reveal one costing $3 or more. Put that card into your hand and discard the rest.",
	},
	{
		name : "Storeroom",
		setID : 8,
		isAction : true,
		cost : 3,
		buys: 1,
		description : "Discard any number of cards. +1 Card per card discarded. Discard any number of cards. +$1 per card discarded the second time.",
	},
	{
		name : "Urchin",
		setID : 8,
		isAction : true,
		isAttack : true,
		cost : 3,
		cards: 1,
		actions: 1,
		description : "[Action] Each other player discards down to 4 cards in hand. [Attack] When you play another Attack card with this in play, you may trash this. If you do, gain a Mercenary from the Mercenary pile.",
	},
	{
		name : "Armory",
		setID : 8,
		isAction : true,
		cost : 4,
		description : "Gain a card costing up to $4. Put it on top of your deck.",
	},
	{
		name : "Death Cart",
		setID : 8,
		isAction : true,
		isLooter : true,
		isTrasher: true,
		cost : 4,
		coins : 5,
		description : "[Action]: You may trash an Action card from your hand. If you donÕt, trash this. [Gain]: When you gain this, gain two Ruins.",
	},
	{
		name : "Feodum",
		setID : 8,
		isVictory : true,
		cost : 4,
		description : "[Action]: Worth 1 VP for every 3 Silvers in your deck. [Trash]: When you trash this, gain 3 Silvers.",
	},
	{
		name : "Fortress",
		setID : 8,
		isAction : true,
		cost : 4,
		cards: 1,
		actions: 2,
		description : "[Trash]: When you trash this, gain 3 Silvers.",
	},
	{
		name : "Ironmonger",
		setID : 8,
		isAction : true,
		cost : 4,
		cards: 1,
		actions: 1,
		description : "Reveal the top card of your deck; you may discard it. If it is an Action card, +1 Action; a Treasure card, +$1; a Victory card, +1 Card.",
	},
	{
		name : "Marauder",
		setID : 8,
		isAction : true,
		isAttack : true,
		isLooter : true,
		cost : 4,
		description : "Gain a Spoils. Each other player gains a Ruins.",
	},
	{
		name : "Procession",
		setID : 8,
		isAction : true,
		cost : 4,
		description : "You may play an Action card from your hand twice. Trash it. Gain an Action card costing exactly $1 more than it.",
	},
	{
		name : "Rats",
		setID : 8,
		isAction : true,
		isTrasher: true,
		cost : 4,
		cards: 1,
		actions: 1,
		description : "[Action]: Gain a Rats. Trash a card from your hand other than a Rats (or reveal a hand of all Rats). [Trash]: When this is trashed, +1 Card.",
	},
	{
		name : "Scavenger",
		setID : 8,
		isAction : true,
		cost : 4,
		coins: 2,
		description : "You may put your deck into your discard pile. Look through your discard pile and put one card from it on top of your deck.",
	},
	{
		name : "Wandering Minstrel",
		setID : 8,
		isAction : true,
		cost : 4,
		cards: 1,
		actions: 2,
		description : "Reveal the top 3 cards of your deck. Put the Actions back on top in any order and discard the rest.",
	},
	{
		name : "Band of Misfits",
		setID : 8,
		isAction : true,
		cost : 5,
		description : "Play this as if it were an Action card in the Supply costing less than it that you choose. This is that card until it leaves play.",
	},
	{
		name : "Bandit Camp",
		setID : 8,
		isAction : true,
		cost : 5,
		cards: 1,
		actions: 2,
		description : "Gain a Spoils.",
	},
	{
		name : "Catacombs",
		setID : 8,
		isAction : true,
		cost : 5,
		description : "[Action]: Look at the top 3 cards of your deck. Choose one: Put them into your hand; or discard them and +3 Cards. [Trash]: When you trash this, gain a cheaper card.",
	},
	{
		name : "Count",
		setID : 8,
		isAction : true,
		isTrasher: true,
		cost : 5,
		description : "Choose one: Discard 2 cards; put a card from your hand on top of your deck; or gain a Copper. Choose one: +$3; trash your hand; or gain a Duchy.",
	},
	{
		name : "Counterfeit",
		setID : 8,
		isTreasure : true,
		cost : 5,
		coins: 1,
		buys: 1,
		description : "When you play this, you may play a treasure from your hand twice. If you do, trash that treasure.",
	},
	{
		name : "Cultist",
		setID : 8,
		isAction : true,
		isAttack : true,
		isLooter : true,
		cost : 5,
		cards: 2,
		description : "[Action]: Each other player gains a Ruins. You may play a Cultist from your hand. [Trash]: When you trash this, +3 Cards.",
	},
	{
		name : "Graverobber",
		setID : 8,
		isAction : true,
		cost : 5,
		description : "Choose one: Gain a card from the trash costing from $3 to $6, putting it on top of your deck; or trash an Action card from your hand and gain a card costing up to $3 more than it.",
	},
	{
		name : "Junk Dealer",
		setID : 8,
		isAction : true,
		isTrasher: true,
		cost : 5,
		cards: 1,
		actions: 1,
		coins: 1,
		description : "Trash a card from your hand.",
	},
	{
		name : "Mystic",
		setID : 8,
		isAction : true,
		cost : 5,
		actions: 1,
		coins: 2,
		description : "Name a card. Reveal the top card of your deck. If itÕs the named card, put it into your hand.",
	},
	{
		name : "Pillage",
		setID : 8,
		isAction : true,
		isAttack : true,
		cost : 5,
		description : "Trash this. Each other player with 5 or more cards in hand reveals his hand and discards a card that you choose. Gain 2 Spoils.",
	},
	{
		name : "Rebuild",
		setID : 8,
		isAction : true,
		cost : 5,
		description : "Name a card. Reveal cards from the top of your deck until you reveal a Victory card that is not the named card. Discard the other cards. Trash the Victory card and gain a Victory card costing up to $3 more than it.",
	},
	{
		name : "Rogue",
		setID : 8,
		isAction : true,
		isAttack : true,
		cost : 5,
		coins: 2,
		description : "If there are any cards in the trash costing from $3 to $6, gain one of them. Otherwise, each other player reveals the top 2 cards of his deck, trashes one of them costing from $3 to $6, and discards the rest.",
	},
	{
		name : "Altar",
		setID : 8,
		isAction : true,
		cost : 6,
		description : "Trash a card from your hand. Gain a card costing up to $5.",
	},
	{
		name : "Hunting Grounds",
		setID : 8,
		isAction : true,
		cost : 6,
		cards: 4,
		description : "[Trash]: When this is trashed, gain a Duchy or 3 Estates.",
	},
	{
		name : "Knights",
		setID : 8,
		isAction : true,
		isAttack : true,
		cost : 5,
		description : "One of each, all shuffled into one Kingdom pile.",
	},
	{
		name : "Candlestick Maker",
		setID : 9,
		isAction : true,
		cost : 2,
		actions: 1,
		buys: 1,
		description : "Take a Coin token.",
	},
	{
		name : "Stonemason",
		setID : 9,
		isAction : true,
		cost : 2,
		overpay : true,
		description : "[Action]: Trash a card from your hand. Gain 2 cards each costing less than it. [Overpay]: When you buy this, you may overpay for it. If you do, gain 2 Action cards each costing the amount you overpaid.",
	},
	{
		name : "Doctor",
		setID : 9,
		isAction : true,
		isTrasher: true,
		cost : 3,
		overpay : true,
		description : "[Action]: Name a card. Reveal the top 3 cards of your deck. Trash the matches. Put the rest back on top in any order. [Overpay]: When you buy this, you may overpay for it. For each $1 you overpaid, look at the top card of your deck; trash it, discard it, or put it back.",
	},
	{
		name : "Masterpiece",
		setID : 9,
		isTreasure : true,
		cost : 3,
		overpay : true,
		coins : 1,
		description : "When you buy this, you may overpay for it. If you do, gain a Silver per $1 you overpaid.",
	},
	{
		name : "Advisor",
		setID : 9,
		isAction : true,
		cost : 4,
		actions : 1,
		description : "Reveal the top 3 cards of your deck. The player to your left chooses one of them. Discard that card. Put the other cards into your hand.",
	},
	{
		name : "Herald",
		setID : 9,
		isAction : true,
		cost : 4,
		overpay : true,
		cards : 1,
		actions : 1,
		description : "[Action]: Reveal the top card of your deck. If it is an Action, play it. [Overpay]: When you buy this, you may overpay for it. For each $1 you overpaid, look through your discard pile and put a card from it on top of your deck.",
	},
	{
		name : "Plaza",
		setID : 9,
		isAction : true,
		cost : 4,
		cards : 1,
		actions : 2,
		description : "You may discard a Treasure card. If you do, take a Coin token.",
	},
	{
		name : "Taxman",
		setID : 9,
		isAction : true,
		isAttack : true,
		cost : 4,
		description : "You may trash a Treasure from your hand. Each other player with 5 or more cards in hand discards a copy of it (or reveals a hand without it). Gain a Treasure card costing up to $3 more than the trashed card, putting it on top of your deck.",
	},
	{
		name : "Baker",
		setID : 9,
		isAction : true,
		cost : 5,
		cards : 1,
		actions : 1,
		description : "[Action]: Take a Coin token. [Setup]: Setup: Each player takes a Coin token.",
	},
	{
		name : "Butcher",
		setID : 9,
		isAction : true,
		cost : 5,
		description : "Take 2 Coin tokens. You may trash a card from your hand and then pay any number of Coin tokens. If you did trash a card, gain a card with a cost of up to the cost of the trashed card plus the number of Coin tokens you paid.",
	},
	{
		name : "Journeyman",
		setID : 9,
		isAction : true,
		cost : 5,
		description : "Name a card. Reveal cards from the top of your deck until you reveal 3 cards that are not the named card. Put those cards into your hand and discard the rest.",
	},
	{
		name : "Merchant Guild",
		setID : 9,
		isAction : true,
		cost : 5,
		coins : 1,
		buys : 1,
		description : "While this is in play, when you buy a card, take a Coin token.",
	},
	{
		name : "Soothsayer",
		setID : 9,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 5,
		description : "Gain a Gold. Each other player gains a Curse. Each player who did draws a card.",
	},

	{
		name : "Coin of the Realm",
		setID : 10,
		isTreasure : true,
		isReserve : true,
		cost : 2,
		coins : 1,
		description : "When you play this, put it on your Tavern mat. [Reserve]: Directly after resolving an Action, you may call this, for +2 Actions.",
	},
	{
		name : "Page",
		setID : 10,
		isAction : true,
		isTraveller : true,
		cost : 2,
		actions : 1,
		cards : 1,
		description : "When you discard this from play, you may exchange it for a Treasure Hunter.",
	},
	{
		name : "Peasent",
		setID : 10,
		isAction : true,
		isTraveller : true,
		cost : 2,
		buys : 1,
		coins : 1,
		description : "When you discard this from play, you may exchange it for a Soldier.",
	},
	{
		name : "Ratcatcher",
		setID : 10,
		isAction : true,
		isReserve : true,
		isTrasher: true,
		cost : 2,
		actions : 1,
		cards : 1,
		description : "Put this on your Tavern mat. [Reserve]: At the start of your turn you may call this, to trash a card from your hand.",
	},
	{
		name : "Raze",
		setID : 10,
		isAction : true,
		isTrasher: true,
		cost : 2,
		actions : 1,
		description : "Trash this or a card from your hand. Look at a number of cards from the top of your deck equal to the cost in coins of the trashed card. Put one into your hand and discard the rest.",
	},
	{
		name : "Amulet",
		setID : 10,
		isAction : true,
		isDuration : true,
		isTrasher: true,
		cost : 3,
		description : "Now and at the start of your next turn, choose one: +1 coin; or trash a card from your hand; or gain a Silver.",
	},
	{
		name : "Caravan Guard",
		setID : 10,
		isAction : true,
		isDuration : true,
		isReaction : true,
		cost : 3,
		actions : 1,
		cards : 1,
		description : "At the start of your next turn, +1 coin. [Reaction]: When another player plays an Attack card, you may play this from your hand. (+1 Action has no effect if it's not your turn.",
	},
	{
		name : "Dungeon",
		setID : 10,
		isAction : true,
		isDuration : true,
		cost : 3,
		actions : 1,
		cards : 2,
		description : "Now and at the start of your next turn: +2 Cards, then discard 2 cards.",
	},
	{
		name : "Gear",
		setID : 10,
		isAction : true,
		isDuration : true,
		cost : 3,
		cards: 2,
		description : "Set aside  up to 2 cards from your hand face down. At the start of your next turn, put them into your hand.",
	},
	{
		name : "Guide",
		setID : 10,
		isAction : true,
		isReserve : true,
		cost : 3,
		actions : 1,
		cards: 1,
		description : "Put this on your Tavern mat. [Reserve]: At the start of your turn, you may call this , to discard your hand and draw 5 cards.",
	},
	{
		name : "Duplicate",
		setID : 10,
		isAction : true,
		isReserve : true,
		cost : 4,
		description : "Put this on your Tavern mat. [Reserve]: When you gain a card costing up to 6 coins, you may call this, to gain a copy of that card.",
	},
	{
		name : "Magpie",
		setID : 10,
		isAction : true,
		cost : 4,
		actions : 1,
		cards: 1,
		description : "Reveal the top card of your deck. If it's a Treasure, put it into your hand.  If it's an Action or Victory card, gain a Magpie.",
	},
	{
		name : "Messenger",
		setID : 10,
		isAction : true,
		cost : 4,
		buys : 1,
		coins : 2,
		description : "You may put your deck into your discard pile. When this is your first buy in a turn, gain a card costing up to 4 coins, and each other player gains a copy of it.",
	},
	{
		name : "Miser",
		setID : 10,
		isAction : true,
		cost : 4,
		description : "Choose one: Put a Copper from your hand onto your Tavern mat; or +1 coin per Copper on your Tavern mat.",
	},
	{
		name : "Port",
		setID : 10,
		isAction : true,
		cost : 4,
		actions : 2,
		cards: 1,
		description : "When you buy this, gain another Port.",
	},
	{
		name : "Ranger",
		setID : 10,
		isAction : true,
		cost : 4,
		buys : 1,
		description : "Turn your Journey token over (it starts face up).  If it's face up, +5 cards.",
	},
	{
		name : "Transmorgify",
		setID : 10,
		isAction : true,
		isReserve : true,
		cost : 4,
		actions : 1,
		description : "Put this on your Tavern mat. [Reserve]: At the start of your turn, you may call this, to trash a card from your hand, gain a card costing up to 1 coin more than it, and put that card into your hand.",
	},
	{
		name : "Artificer",
		setID : 10,
		isAction : true,
		cost : 5,
		actions : 1,
		cards: 1,
		coins : 1,
		description : "Discard any number of cards. You may gain a card costing exactly 1 coin per card discarded, putting it on the top of your deck.",
	},
	{
		name : "Bridge Troll",
		setID : 10,
		isAction : true,
		isAttack : true,
		isDuration : true,
		cost : 5,
		buys : 1,
		description : "Each player takes his -1 coin token. Now and at the start of your next turn: +1 Buy. While this is in play, cards cost 1 coin less on your turns, but not less than 0 coins.",
	},
	{
		name : "Distant Lands",
		setID : 10,
		isAction : true,
		isReserve : true,
		isVictory : true,
		cost : 5,
		description : "Put this on your Tavern mat. [Victory]: Worth 4 VP if on your Tavern at the end of the game (otherwise worth 0 VP).",
	},
	{
		name : "Giant",
		setID : 10,
		isAction : true,
		isAttack : true,
		isCurser: true,
		cost : 5,
		description : "Turn your Journey token over (it starts face up). If it's face down, +1 coin. If it's face up, +5 coins, and each other player reveals the top card of his deck, trashes it if it costs from 3 to 6 coins, and otherwise discards it and gains a Curse.",
	},
	{
		name : "Haunted Woods",
		setID : 10,
		isAction : true,
		isAttack : true,
		isDuration : true,
		description : "Until your next turn, when any other player buys a card, he puts his hand on top of his deck in any order. At the start of your next turn, +3 cards.",
	},
	{
		name : "Lost City",
		setID : 10,
		isAction : true,
		cost : 5,
		actions : 2,
		cards : 2,
		description : "When you gain this, each other player draws a card.",
	},
	{
		name : "Relic",
		setID : 10,
		isTreasure : true,
		isAttack : true,
		cost : 5,
		coins : 2,
		description : "When you play this, each other player puts his -1 Card token on his deck.",
	},
	{
		name : "Royal Carriage",
		setID : 10,
		isAction : true,
		isReserve : true,
		cost : 5,
		actions : 1,
		description : "Put this on your Tavern mat. [Reserve]: Directly after resolving an Action, if it's still in play, you may call this, to replay that Action.",
	},
	{
		name : "Storyteller",
		setID : 10,
		isAction : true,
		cost : 5,
		actions : 1,
		coins : 1,
		description : "Play up to 3 Treasures from your hand. Pay  all of your coins; +1 Card per coin paid.",
	},
	{
		name : "Swamp Hag",
		setID : 10,
		isAction : true,
		isAttack : true,
		isCurser: true,
		isDuration : true,
		cost : 5,
		description : "Until your next turn, when any other player buys a card, he gains a Curse. At the start of your next turn, +3 coins.",
	},
	{
		name : "Treasure Trove",
		setID : 10,
		isTreasure : true,		
		cost : 5,
		coins : 2,
		description : "When you play this, gain a Gold and a Copper.",
	},
	{
		name : "Wine Merchant",
		setID : 10,
		isAction : true,
		isReserve : true,
		cost : 5,
		buys : 1,
		coins : 4,
		description : "Put this on your Tavern Mat. [Reserve]: At the end of your Buy phase	if you have at least 2 coins unspent, you may discard this from your Tavern mat.",
	},
	{
		name : "Hireling",
		setID : 10,
		isAction : true,
		isDuration : true,
		cost : 6,
		description : "At the start of each of your turns for the rest of the game: +1 Card (this stays in play).",
	},
	{
		name : "Black Market",
		setid: 11,
		isAction : true,
		cost : 3,
		coins : 2,
		description : "Reveal the top 3 cards of the Black Market deck. You may buy one of them immediately. Put the unbought cards on the bottom of the Black Market deck in any order. (Before the game, make a Black Market deck out of one copy of each Kingdom card not in the supply.)",
	},
	{
		name : "Envoy",
		setid: 11,
		isAction : true,
		cost : 4,
		description : "Reveal the top 5 cards of your deck. The player to the left chooses one for you to discard. Draw the rest.",
	}
];

var cardsByName = {};
for(var i in cards) {
	cardsByName[cards[i].name] = cards[i];
}